Check that |version| and |today| are present in each PO file
Fixes #165

diff --git a/translations/Makefile b/translations/Makefile
--- a/translations/Makefile
+++ b/translations/Makefile
@@ -18,11 +18,27 @@ gettext:
 $(SPHINXPROJ).pot: gettext
 	xgettext -o $(SPHINXPROJ).pot $(wildcard $(BUILDDIR)/gettext/*.pot)
 
-split-po:
-	for lang in "$(PO_LINGUAS)"; do \
+check-po:
+	for lang in $(PO_LINGUAS); do \
+		grep -q 'msgstr "|version|"' "$(MERGEDDIR)/$$lang.po"; \
+		if [ $$? -ne 0 ]; then \
+			echo "ERROR: Translation in $(MERGEDDIR)/$$lang.po has no |version|." >&2; \
+			exit 1; \
+		fi; \
+		grep -q 'msgstr "|today|"' "$(MERGEDDIR)/$$lang.po"; \
+		if [ $$? -ne 0 ]; then \
+			echo "ERROR: Translation in $(MERGEDDIR)/$$lang.po has no |today|." >&2; \
+			exit 1; \
+		fi; \
+	done
+
+split-po: check-po
+	for lang in $(PO_LINGUAS); do \
 		echo "$$lang:"; \
 		mkdir -p "$(LOCALEDIR)/$$lang/LC_MESSAGES"; \
 		for src in $(SOURCE_FILES); do \
 			msggrep -N "../$(SOURCEDIR)/$$src.txt" "$(MERGEDDIR)/$$lang.po" > "$(LOCALEDIR)/$$lang/LC_MESSAGES/$$src.po"; \
 		done; \
 	done
+
+.PHONY: check-po gettext split-po
